In [1]:
#Model Building

In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import matplotlib.pyplot as imread
import spacy 
import string
from wordcloud import WordCloud
%matplotlib inline

In [3]:
data = pd.read_csv("hotel_reviews.csv")
data

Review  Rating
0      nice hotel expensive parking got good deal sta...       4
1      ok nothing special charge diamond member hilto...       2
2      nice rooms not 4* experience hotel monaco seat...       3
3      unique, great stay, wonderful time hotel monac...       5
4      great stay great stay, went seahawk game aweso...       5
...                                                  ...     ...
20486  best kept secret 3rd time staying charm, not 5...       5
20487  great location price view hotel great quick pl...       4
20488  ok just looks nice modern outside, desk staff ...       2
20489  hotel theft ruined vacation hotel opened sept ...       1
20490  people talking, ca n't believe excellent ratin...       2

[20491 rows x 2 columns]

In [4]:
# bin the data into negative, neutral, and positive values
bins = [0, 2, 4, 6]

bin_names = ['negative', 'neutral', 'positive']

score_bin = pd.Series(data.Rating, name = 'score')

score = pd.cut(score_bin, bins, labels=bin_names, right=False)

In [5]:
# add the bins into the dataframe

data = pd.concat([data, score], axis=1)

data.head()

Review  Rating     score
0  nice hotel expensive parking got good deal sta...       4  positive
1  ok nothing special charge diamond member hilto...       2   neutral
2  nice rooms not 4* experience hotel monaco seat...       3   neutral
3  unique, great stay, wonderful time hotel monac...       5  positive
4  great stay great stay, went seahawk game aweso...       5  positive

In [7]:
data.loc[:,'Review_cln'] = data['Review']

In [8]:
data

Review  Rating     score  \
0      nice hotel expensive parking got good deal sta...       4  positive   
1      ok nothing special charge diamond member hilto...       2   neutral   
2      nice rooms not 4* experience hotel monaco seat...       3   neutral   
3      unique, great stay, wonderful time hotel monac...       5  positive   
4      great stay great stay, went seahawk game aweso...       5  positive   
...                                                  ...     ...       ...   
20486  best kept secret 3rd time staying charm, not 5...       5  positive   
20487  great location price view hotel great quick pl...       4  positive   
20488  ok just looks nice modern outside, desk staff ...       2   neutral   
20489  hotel theft ruined vacation hotel opened sept ...       1  negative   
20490  people talking, ca n't believe excellent ratin...       2   neutral   

                                              Review_cln  
0      nice hotel expensive parking got good deal sta...  
1      ok nothing special charge diamond member hilto...  
2      nice rooms not 4* experience hotel monaco seat...  
3      unique, great stay, wonderful time hotel monac...  
4      great stay great stay, went seahawk game aweso...  
...                                                  ...  
20486  best kept secret 3rd time staying charm, not 5...  
20487  great location price view hotel great quick pl...  
20488  ok just looks nice modern outside, desk staff ...  
20489  hotel theft ruined vacation hotel opened sept ...  
20490  people talking, ca n't believe excellent ratin...  

[20491 rows x 4 columns]

In [9]:
import re

In [10]:
import nltk
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [11]:
pip install pyspellchecker

In [12]:
pip install emot

Note: you may need to restart the kernel to use updated packages.


In [13]:
from textblob import TextBlob
from spellchecker import SpellChecker
from emot.emo_unicode import UNICODE_EMOJI # For emojis
from emot.emo_unicode import EMOTICONS_EMO # For EMOTICONS

In [14]:
from collections import Counter

In [15]:
data.head(5)

Review  Rating     score  \
0  nice hotel expensive parking got good deal sta...       4  positive   
1  ok nothing special charge diamond member hilto...       2   neutral   
2  nice rooms not 4* experience hotel monaco seat...       3   neutral   
3  unique, great stay, wonderful time hotel monac...       5  positive   
4  great stay great stay, went seahawk game aweso...       5  positive   

                                          Review_cln  
0  nice hotel expensive parking got good deal sta...  
1  ok nothing special charge diamond member hilto...  
2  nice rooms not 4* experience hotel monaco seat...  
3  unique, great stay, wonderful time hotel monac...  
4  great stay great stay, went seahawk game aweso...

In [16]:
data = data.rename({'Review':'review','Rating':'rating'},axis=1)
data.head()

review  rating     score  \
0  nice hotel expensive parking got good deal sta...       4  positive   
1  ok nothing special charge diamond member hilto...       2   neutral   
2  nice rooms not 4* experience hotel monaco seat...       3   neutral   
3  unique, great stay, wonderful time hotel monac...       5  positive   
4  great stay great stay, went seahawk game aweso...       5  positive   

                                          Review_cln  
0  nice hotel expensive parking got good deal sta...  
1  ok nothing special charge diamond member hilto...  
2  nice rooms not 4* experience hotel monaco seat...  
3  unique, great stay, wonderful time hotel monac...  
4  great stay great stay, went seahawk game aweso...

In [17]:
df = data[['score', 'review']]
df.head(10)

score                                             review
0  positive  nice hotel expensive parking got good deal sta...
1   neutral  ok nothing special charge diamond member hilto...
2   neutral  nice rooms not 4* experience hotel monaco seat...
3  positive  unique, great stay, wonderful time hotel monac...
4  positive  great stay great stay, went seahawk game aweso...
5  positive  love monaco staff husband stayed hotel crazy w...
6  positive  cozy stay rainy city, husband spent 7 nights m...
7  positive  excellent staff, housekeeping quality hotel ch...
8  positive  hotel stayed hotel monaco cruise, rooms genero...
9  positive  excellent stayed hotel monaco past w/e delight...

In [18]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus=[]
for i in range(0,20491):
    
    review=re.sub('[^a-zA-Z]',' ',df['review'][i])
    review=review.lower()
    review=review.split()
    ps=PorterStemmer()
    all_stopwords=stopwords.words('english')
    all_stopwords.remove('not')
    review=[ps.stem(word) for word in review if not word in set (all_stopwords)]
    review=' '.join(review)
    corpus.append(review)

[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>


In [19]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=20000)
df = pd.read_csv('Hotel_reviews.csv')
X=cv.fit_transform(corpus).toarray()
y=data['score']

In [20]:
len(X[0])

20000

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# Naive_bayes Algorithm

In [22]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train,y_train)

GaussianNB()

In [23]:
y_pred=classifier.predict(x_test)

In [24]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[  79   97  109]
 [ 179  275  372]
 [ 481  942 1565]]


0.46816296657721396

# Logistic Regression

In [25]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

C:\anacoda\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [26]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix , accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[ 171  100   14]
 [  88  482  256]
 [   9  204 2775]]


0.8363015369602342

# KNN ALGORITHM

In [27]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [28]:
y_pred=classifier.predict(x_test)
from sklearn.metrics import confusion_matrix , accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[  88   46  151]
 [  81  154  591]
 [  36  110 2842]]


0.7523786289338863

# RandomForest Algorithm

In [29]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [30]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
#accuracy_score(y_test, y_pred)
print(accuracy_score(y_test, y_pred))

[[  70   83  132]
 [  28  200  598]
 [   8   99 2881]]
0.7687240790436692


In [31]:
from  sklearn.model_selection import train_test_split
Independent_var = data.Review_cln
Dependent_var = data.score

IV_train, IV_test, DV_train, DV_test = train_test_split(Independent_var, Dependent_var, test_size = 0.2)

print('IV_train : ', len(IV_train))
print('IV_test : ', len(IV_test))
print('DV_train : ', len(IV_train))
print('DV_test : ', len(IV_test))

IV_train :  16392
IV_test :  4099
DV_train :  16392
DV_test :  4099


In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
tvec = TfidfVectorizer()
clf2 = LogisticRegression(solver="lbfgs")

from sklearn.pipeline import Pipeline

In [33]:
model = Pipeline([('vectorizer',tvec),('classifier',clf2)])

model.fit(IV_train,DV_train)

C:\anacoda\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('classifier', LogisticRegression())])

In [34]:
from sklearn.metrics import confusion_matrix

predictions = model.predict(IV_test)

confusion_matrix(predictions,DV_test)

array([[ 125,   34,    4],
       [ 101,  480,   80],
       [  27,  310, 2938]], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

print("Accuracy : ", accuracy_score(predictions, DV_test))
print("Precision : ", precision_score(predictions, DV_test, average='weighted'))
print("Recall : ", recall_score(predictions, DV_test, average='weighted'))

Accuracy :  0.8643571602829958
Precision :  0.8903512348553798
Recall :  0.8643571602829958


In [36]:
#Prediction 
ex = ["Great location, really pleasant and clean rooms, but the thing that makes this such a good place to stay are the staff. All of the people are incredibly helpful and advice."]

result = model.predict(ex)
print(result)

['positive']
